sudo: false

language: python

python:
   - "3.5"

before_install:
   - pip install --upgrade pip
   - psql -c 'create database test;' -U postgres

addons:
   postgresql: "9.4"

install: true

script:
   - make
   - nosetests tests.py

env:
   - SWE_IDB_PGDB_ADDR="localhost:5432"
   - SQE_IDB_PGDB_TABLE="test"

services:
   - postgresql