FORMAT: 1A
HOST: http://artisttree.me/api

# ArtistTree API

The ArtistTree API is a basic API built from the Rijksmuseum data, focused on art and artworks from history.


## Get all artists [/artists/all]

### List All Artists [GET]

+ Response 200 (application/json)

        [
            {
                "artists": [
                    {
                        "name": "Vincent VanGogh",
                        "dateOfBirth": "1853-3-30",
                        "dateOfDeath": "1890-7-29",
                        "nationality": "Dutch",
                        "countryOfOrigin": "The Netherlands",
                        "image": ""
                    },
                   {
                    "name": "Johannes Vermeer",
                    "dateOfBirth": "1632-10-31",
                    "dateOfDeath": "1675-12-15",
                    "nationality": "Noord-Nederlands",
                    "countryOfOrigin": "Dutch Republic",
                    "image": ""
                    }
                ]
                
            }
        ]

## Questions Collection [/questions]

### List All Questions [GET]

+ Response 200 (application/json)

        [
            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 2048
                    }, {
                        "choice": "Python",
                        "votes": 1024
                    }, {
                        "choice": "Objective-C",
                        "votes": 512
                    }, {
                        "choice": "Ruby",
                        "votes": 256
                    }
                ]
            }
        ]

### Create a New Question [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "question": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }