runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3

# Use env_variables locally to set a password via environment variables
#  or do so manually by setting an environment variable in console or globally
# Please do not put passwords in source control
env_variables:
  SWE_IDB_PGDB_ADDR: ''
  SWE_IDB_PGDB_PW: uB6b5eFnexydPnm1
  SWE_IDB_PGDB_OPTS: /?host=/cloudsql/
    cs373-project-345:us-central1:idb-artistree

beta_settings:
  cloud_sql_instances: cs373-project-345:us-central1:idb-artistree
