runtime: python
env: flex
api_version: 1
entrypoint: gunicorn -c gunicorn.conf.py -b :$PORT

runtime_config:
  python_version: 3

threadsafe: true

# Set the password environment variable on local machine to prevent exposing
# Use '?unix_socket=/cloudsql/cs373-project-345:us-central1:idb-artistree:
#  us-central1:idb-artistree' for local DB testing with the Cloud SQL proxy

beta_settings:
  cloud_sql_instances: idb-artistree
