FORMAT: 1A
HOST: http://artisttree.me/api

# ArtistTree API

The ArtistTree API is a basic API built from the Rijksmuseum data, focused on art and artworks from history.

When we spent some time looking at our API, we determined that for the most part, it was pretty alright as it
stood at the end of last phase. We've added a couple of search functions for specific models though, to give 
more options to our users. Our data is really — for  the most part anyways — a polite and logical repacking 
of the Rijksmuseum data, and our API makes it available in a much more digestible format than we found it in. 
We've also added/plan to add additional data scraped from wikipedia or other similar sources where possible, which
will be retrievable via our API if and when that data is available. Search options should be pretty granular if you
need them to be -- think of the search functions like externally available queries of our database.

### A brief note about searching using our API:

For any search request, you MUST provide one of the fields. But any additional fields are optional. 
The search will attempt to narrow down the results using all the fields you provide, so if one of the fields
is invalid or nothing comes back for that field, we'll search using the other fields. We combine search results
across all fields given, so if you include a specific name and a set of colors, you'll get the artwork matching 
that name and all artworks that have similar colors.

## Get all artists [/artists/all]

### List All Artists [GET]

This call just provides a list of all the artists we have in our database. (This may be a sizable request!)

+ Response 200 (application/json)

        [
            {
                "artists": [
                    {
                        "name": "Vincent VanGogh",
                        "dateOfBirth": "1853-3-30",
                        "dateOfDeath": "1890-7-29",
                        "nationality": "Dutch",
                        "countryOfOrigin": "The Netherlands",
                        "image": "",
                        "bio":"lorem ipsum"
                    },
                   {
                    "name": "Johannes Vermeer",
                    "dateOfBirth": "1632-10-31",
                    "dateOfDeath": "1675-12-15",
                    "nationality": "Noord-Nederlands",
                    "countryOfOrigin": "Dutch Republic",
                    "image": "",
                    "bio":"lorem ipsum"
                    }
                ]
                
            }
        ]

## Get Specific Artist [/artists/search/]

### Retrieve a specific artist [POST]

This call is intended to retrieve an artist based on certain search criteria. 
You MUST include one of the fields in your request, but the rest are optional. 
Returns a list of artist objects.

+ Request (application/json)
        
        {
            "name": "Vincent VanGogh",
            "era": "1600",
            "nationality": "Dutch"
        }
        
+ Response 201 (application/json)

        [
            {
                "artists": [
                    {
                        "name": "Vincent VanGogh",
                        "dateOfBirth": "1853-3-30",
                        "dateOfDeath": "1890-7-29",
                        "nationality": "Dutch",
                        "countryOfOrigin": "The Netherlands",
                        "image": ""
                        "bio":""
                    }
                ]
            }
        ]
        
## Get all artworks [/works/all]

### List all artworks [GET]

Returns a list of all our artworks.

+ Response 200 (application/json)

        [
            {
                "works":[
                    {
                    "name":"Night Watch",
                    "physicalMedium": "oil on canvas",
                    "year": 1642,
                    "style": "",
                    "dimensions": [
                      {
                        "unit": "cm",
                        "type": "height",
                        "part": null,
                        "value": "379.5"
                      },
                      {
                        "unit": "cm",
                        "type": "width",
                        "part": null,
                        "value": "453.5"
                      }
                    ],
                    "colors": [
                      "#261808",
                      " #5E3C14",
                      " #9C8238",
                      " #885617",
                      " #AF9F6B",
                      " #6C6238",
                      " #D7CB9E"
                    ],
                    "image": "http://lh6.ggpht.com/ZYWwML8mVFonXzbmg2rQBulNuCSr3rAaf5ppNcUc2Id8qXqudDL1NSYxaqjEXyDLSbeNFzOHRu0H7rbIws0Js4d7s_M=s0",
                    "motifs": null
                    },
                    {
                    "name":"Self Portrait"
                    "physicalMedium": "painting",
                    "year": 1887,
                    "style": "",
                    "dimensions": [
                      {
                        "unit": "cm",
                        "type": "height",
                        "part": null,
                        "value": "42"
                      },
                      {
                        "unit": "cm",
                        "type": "width",
                        "part": null,
                        "value": "34"
                      },
                      {
                        "unit": "cm",
                        "type": "depth",
                        "part": null,
                        "value": "8"
                      }
                    ],
                    "colors": [
                      "#52686D",
                      " #50524C",
                      " #9CA097",
                      " #936D59",
                      " #C2C1B8",
                      " #6A84A2",
                      " #2F3031"
                    ],
                    "image": "http://lh4.ggpht.com/RKAJ3z2mOcw83Ju0a7NIp71oUoJbVWJQzxwki5PSERissvWIrELCuxxGZ12U0PeAnf6WLkRCzpFdvjweUBjlcr2I4dl_=s0",
                    "motifs": null
                    }
                ]
                
            }
        ]


## Get a specifc work of art [/works/search]

### Get a specific work of art [POST]

Same as the search for artists, this will search our artworks. One field is required, but the others are optional.
Rather than search for the colors you give us exactly, we'll return works with similar colors.  

+ Request (application/json)
        
        {
            "name": "Night Watch",
            "era": "18th century",
            "year": 1887,
            "colors":[
            "#885617",
            "#9CA097"
            ]
            
        }

+ Response 201 (application/json)

        [
            {
                "works":[
                    {
                    "name":"Night Watch",
                    "physicalMedium": "oil on canvas",
                    "year": 1642,
                    "style": "",
                    "dimensions": [
                      {
                        "unit": "cm",
                        "type": "height",
                        "part": null,
                        "value": "379.5"
                      },
                      {
                        "unit": "cm",
                        "type": "width",
                        "part": null,
                        "value": "453.5"
                      }
                    ],
                    "colors": [
                      "#261808",
                      " #5E3C14",
                      " #9C8238",
                      " #885617",
                      " #AF9F6B",
                      " #6C6238",
                      " #D7CB9E"
                    ],
                    "image": "http://lh6.ggpht.com/ZYWwML8mVFonXzbmg2rQBulNuCSr3rAaf5ppNcUc2Id8qXqudDL1NSYxaqjEXyDLSbeNFzOHRu0H7rbIws0Js4d7s_M=s0"
                    }
                ]
            }
        ]

## Get all eras [/eras/all]

### List all eras [GET]

Gives you all the data we have for the different eras/periods.

+ Response 200 (application/json)

        [
            {
                "eras":[
                    {
                    "era":"17th century",
                    "artists": [
                      "Rembrandt Harmensz. van Rijn",
                      "Johannes Vermeer"
                    ],
                    "works": [
                      "The Milkmaid",
                      "Night Watch"
                    ],
                    "styles": [
                      ""
                    ],
                    "countries": [
                      "Dutch Republic",
                      "Italy"
                    ],
                    "mediums": [
                      "oil on canvas",
                      "paiting"
                    ]
                    },
                    {
                    "era":"18th century",
                    "artists": [
                      "Cornelis Troost",
                      "Jean-Étienne Liotard"
                    ],
                    "works": [
                      "Portrait of a Member of the Van der Mersch Family",
                      "Portret van Marie Fargues"
                    ],
                    "styles": [
                      ""
                    ],
                    "countries": [
                      "Netherlands",
                      "France"
                    ],
                    "mediums": [
                      "oil on panel",
                      "pastel and watercolor",
                      "parchment"
                    ]
                    },
                    {
                    "era": "19th century",
                    "artists": [
                      "Vincent van Gogh",
                      "Jan Willem Pieneman"
                    ],
                    "works": [
                      "Self Portrait",
                      "Triumvirate Assuming Power in the Name of the Prince of Orange"
                    ],
                    "styles": [
                      ""
                    ],
                    "countries": [
                      "Netherlands",
                      "Japan"
                    ],
                    "mediums": [
                      "oil on canvas",
                      "painting",
                      "parchment"
                    ]
                    }
                ]
            }
        ]
        
## Get a specific era [/eras/search]

### Get specific era [POST]

+ Request (application/json)
        
        {
            "name": "17th century",
            "type": "century",
            "countries": [
                "Italy",
                "Dutch Republic"
            ],
            "artists": [
                "Rembrandt Harmensz. van Rijn"
            ],
            "works":[
                "Night Watch"
            ],
            "media":[
                "oil on canvas"
            ]
            
        }
        
+ Response 201 (application/json)

        [
            {
                "eras":[
                    {
                        "era":"17th century",
                        "artists": [
                          "Rembrandt Harmensz. van Rijn",
                          "Johannes Vermeer"
                        ],
                        "works": [
                          "The Milkmaid",
                          "Night Watch"
                        ],
                        "countries": [
                          "Dutch Republic",
                          "Italy"
                        ],
                        "mediums": [
                          "oil on canvas",
                          "painting"
                        ]
                    }
            }
        ]
        
## Get all mediums [/mediums/all]

### Get all mediums [GET]

Returns a list of all of the mediums of art represented in our database.

+ Response 200 (application/json)
        
        [
            {
                "mediums": [
                    {
                    "name": "Sculpture",
                    "colors": [
                      " #261808",
                      " #5E3C14",
                      " #9C8238",
                      " #885617",
                      " #AF9F6B",
                      " #6C6238",
                      " #D7CB9E"
                    ],
                    "averageage": "312",
                    "artists": [
                      "Rembrandt Harmensz. van Rijn"
                    ],
                    "avgdimensions": [
                      {
                        "unit": "cm",
                        "type": "height",
                        "part": null,
                        "value": "359.5"
                      },
                      {
                        "unit": "cm",
                        "type": "width",
                        "part": null,
                        "value": "253.5"
                      }
                    ],
                    "images": [
                      "http://lh6.ggpht.com/ZYWwML8mVFonXzbmg2rQBulNuCSr3rAaf5ppNcUc2Id8qXqudDL1NSYxaqjEXyDLSbeNFzOHRu0H7rbIws0Js4d7s_M=s0",
                      "http://lh3.ggpht.com/XUw3NdeiA0MsT-mygp8NT1oPUd17GB3BK2nSRYvyTAY-N64KwsLOO5QU3muSDEk2AdMzonIVLgjge581mOobVqsQrA=s0"
                      
                    ]
                    },
                    {
                    "name":"Oil on canvas",
                    "colors": [
                      "#52686D",
                      " #50524C",
                      " #9CA097",
                      " #936D59",
                      " #C2C1B8",
                      " #6A84A2",
                      " #2F3031"
                    ],
                    "averageage": "112",
                    "artists": [
                      "Vincent van Gogh"
                    ],
                    "avgdimensions": [
                      {
                        "unit": "cm",
                        "type": "height",
                        "part": null,
                        "value": "55.5"
                      },
                      {
                        "unit": "cm",
                        "type": "width",
                        "part": null,
                        "value": "30.5"
                      }
                    ],
                    "images": [
                      "http://lh4.ggpht.com/RKAJ3z2mOcw83Ju0a7NIp71oUoJbVWJQzxwki5PSERissvWIrELCuxxGZ12U0PeAnf6WLkRCzpFdvjweUBjlcr2I4dl_=s0"
                    ]
                    }
                
                ]
            }
        
        ]
